#!/usr/bin/env python3
"""
Build script to embed sys/ directory into the kernel filesystem.
Generates sysfs_data.c which contains all files from sys/ directory.
"""

import os
import sys

def escape_c_string(s):
    """Escape a string for use in C source code."""
    result = []
    for c in s:
        if c == '\\':
            result.append('\\\\')
        elif c == '"':
            result.append('\\"')
        elif c == '\n':
            result.append('\\n')
        elif c == '\r':
            result.append('\\r')
        elif c == '\t':
            result.append('\\t')
        elif ord(c) >= 32 and ord(c) < 127:
            result.append(c)
        else:
            result.append(f'\\x{ord(c):02x}')
    return ''.join(result)

def collect_files(base_dir):
    """Collect all files from sys/ directory, preserving structure."""
    files = []
    base_len = len(base_dir)
    
    for root, dirs, filenames in os.walk(base_dir):
        # Skip hidden files and directories
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        filenames = [f for f in filenames if not f.startswith('.')]
        
        for filename in filenames:
            filepath = os.path.join(root, filename)
            rel_path = filepath[base_len:].lstrip('/')
            files.append((rel_path, filepath))
    
    return files

def generate_c_file(files, output_file):
    """Generate C source file with embedded file data."""
    with open(output_file, 'w') as f:
        f.write("/* Auto-generated file system data from sys/ directory */\n")
        f.write("/* DO NOT EDIT - Generated by build_sysfs.py */\n\n")
        f.write("#include \"kernel.h\"\n\n")
        
        # Generate file data arrays
        file_vars = []
        for i, (rel_path, filepath) in enumerate(files):
            var_name = f"sysfs_file_{i}"
            size_var = f"sysfs_file_{i}_size"
            is_binary = rel_path.endswith('.16i')
            
            with open(filepath, 'rb') as infile:
                content = infile.read()
            
            file_vars.append((var_name, size_var, rel_path, len(content), is_binary))
            
            f.write(f"/* {rel_path} */\n")
            if is_binary:
                # Binary files: use unsigned char array
                f.write(f"static const unsigned char {var_name}[] = {{")
                for j, byte in enumerate(content):
                    if j % 16 == 0:
                        f.write("\n    ")
                    f.write(f"0x{byte:02x}")
                    if j < len(content) - 1:
                        f.write(",")
                    if j % 16 != 15 and j < len(content) - 1:
                        f.write(" ")
                f.write(f"\n}};\n")
                f.write(f"static const size_t {size_var} = {len(content)};\n\n")
            else:
                # Text files: use string literal
                f.write(f"static const char {var_name}[] = \"")
                for byte in content:
                    if byte == ord('\\'):
                        f.write('\\\\')
                    elif byte == ord('"'):
                        f.write('\\"')
                    elif byte == ord('\n'):
                        f.write('\\n')
                    elif byte == ord('\r'):
                        f.write('\\r')
                    elif byte == ord('\t'):
                        f.write('\\t')
                    elif byte >= 32 and byte < 127:
                        f.write(chr(byte))
                    else:
                        f.write(f'\\x{byte:02x}')
                f.write("\";\n\n")
        
        # Generate initialization function
        f.write("/* Initialize filesystem with files from sys/ directory */\n")
        f.write("void sysfs_initialize(void) {\n")
        f.write("    /* Start in /sys directory (already created by kernel) */\n")
        
        # Track current directory to avoid redundant chdirs
        current_path = ["sys"]
        
        for var_name, size_var, rel_path, file_size, is_binary in file_vars:
            # Parse path and create directories/files
            parts = rel_path.split('/')
            filename = parts[-1]
            dir_parts = parts[:-1]
            
            # Build target path
            target_path = ["sys"] + dir_parts
            
            # Navigate to target directory
            # Find common prefix
            common_len = 0
            for i in range(min(len(current_path), len(target_path))):
                if current_path[i] == target_path[i]:
                    common_len = i + 1
                else:
                    break
            
            # Go back to common ancestor
            if common_len < len(current_path):
                steps_back = len(current_path) - common_len
                for _ in range(steps_back):
                    f.write("    fs_chdir(\"..\");\n")
                current_path = current_path[:common_len]
            
            # Navigate forward to target
            for i in range(common_len, len(target_path)):
                dir_part = target_path[i]
                if dir_part:
                    f.write(f"    fs_mkdir(\"{dir_part}\");\n")
                    f.write(f"    fs_chdir(\"{dir_part}\");\n")
                    current_path.append(dir_part)
            
            # Create file (use binary function for binary files, regular for text files)
            if is_binary:
                f.write(f"    fs_create_file_binary(\"{filename}\", {var_name}, {size_var});\n")
            else:
                f.write(f"    fs_create_file(\"{filename}\", {var_name});\n")
        
        f.write("}\n")

def main():
    base_dir = "sys"
    output_file = "sysfs_data.c"
    
    if not os.path.exists(base_dir):
        print(f"Warning: {base_dir} directory does not exist. Creating empty sysfs_data.c")
        with open(output_file, 'w') as f:
            f.write("/* Auto-generated file system data from sys/ directory */\n")
            f.write("/* sys/ directory not found */\n\n")
            f.write("#include \"kernel.h\"\n\n")
            f.write("void sysfs_initialize(void) {\n")
            f.write("    /* No files to load */\n")
            f.write("}\n")
        return 0
    
    files = collect_files(base_dir)
    
    if not files:
        print(f"Warning: No files found in {base_dir} directory")
        with open(output_file, 'w') as f:
            f.write("/* Auto-generated file system data from sys/ directory */\n")
            f.write("/* No files found in sys/ */\n\n")
            f.write("#include \"kernel.h\"\n\n")
            f.write("void sysfs_initialize(void) {\n")
            f.write("    /* No files to load */\n")
            f.write("}\n")
        return 0
    
    print(f"Found {len(files)} file(s) in {base_dir}/")
    for rel_path, _ in files:
        print(f"  - {rel_path}")
    
    generate_c_file(files, output_file)
    print(f"Generated {output_file}")
    return 0

if __name__ == "__main__":
    sys.exit(main())

